### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by marcelk-workstreampeople-com** [PimDoos/ha-sessy#49]
Hi @PimDoos 

When i try to install the integration via the UI.

I get this error:

`Config flow could not be loaded: {"message":"Invalid handler specified"}`

Restarted Home Assistant multiple times
----
Logs:

This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/sessy/__init__.py:21
Integration: Sessy (documentation, issues)
First occurred: 21:13:34 (4 occurrences)
Last logged: 21:16:48

Unexpected exception importing platform custom_components.sessy.config_flow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/sessy/__init__.py", line 21, in <module>
    PLATFORMS: list[Platform] = [Platform.SENSOR, Platform.SELECT, Platform.NUMBER, Platform.TIME, Platform.UPDATE]
  File "/usr/local/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: TIME
----

Do you know what went wrong?

Thanks in advance

**Comment by PimDoos** [comment]
Hi Marcel,
This looks like the 'time' platform is not available. This was introduced in Home Assistant 2023.06. Can you confirm your Home Assistant version?
This integration requires Home Assistant 2023.06 for version [0.4.0](https://github.com/PimDoos/ha-sessy/releases/tag/v0.4.0) and up, [0.3.1](https://github.com/PimDoos/ha-sessy/releases/tag/v0.3.1) was the last version tested on Home Assistant 2023.05.

**Comment by marcelk-workstreampeople-com** [comment]
My current version is 2023.5.4, will upgrade and test again

**Comment by nlmaca** [comment]
Hi,
I have tried it yesterday on 2023.6 at my dads place and had the same error. When i reverted back to 0.3.1 i slowly upgraded until 0.3.3. From 0.4 the error came back again.

I just tried to install it on my own HA. Both HA are running in a docker container. 
Until 0.3.3 works. As soon as i install 0.4.0 it will return the error. 


And have the same error 
Home Assistant 2023.3.3
Frontend 20230309.0 - latest

ErrorLog: 
`Logger: homeassistant.loader
Source: custom_components/sessy/__init__.py:21
Integration: Sessy ([documentation](https://github.com/PimDoos/ha-sessy), [issues](https://github.com/PimDoos/ha-sessy/issues))
First occurred: 10:38:11 (1 occurrences)
Last logged: 10:38:11

Unexpected exception importing platform custom_components.sessy.config_flow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 779, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 796, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/sessy/__init__.py", line 21, in <module>
    PLATFORMS: list[Platform] = [Platform.SENSOR, Platform.SELECT, Platform.NUMBER, Platform.TIME, Platform.UPDATE]
  File "/usr/local/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: TIME`

and 
`Logger: homeassistant.config_entries
Source: config_entries.py:849
First occurred: 10:38:11 (1 occurrences)
Last logged: 10:38:11

Error occurred loading configuration flow for integration sessy: Exception importing custom_components.sessy.config_flow`

**Comment by PimDoos** [comment]
Hi, this is expected behaviour, 0.4.0 does not support Home Assistant <= 2023.5. Your log shows you're running 2023.3.3

**Comment by nlmaca** [comment]
Maybe i misunderstood, but in your releasenotes 0.4.0 it says: 
Home Assistant: 2023.06.0 and up  (.06.x is lower then 3.3), so i assumed i was in the clear with the HA version

I upgraded the docker container to the latest stable 2023.6.3 and now indeed the error is gone.

**Comment by PimDoos** [comment]
Home Assistant releases follow the version numbering:  year.month.revision. So 2023.06 is newer than 2023.03 :)

**Comment by nlmaca** [comment]
Oh, thx. Never knew that. Thx for the explanation on that. Will keep that in mind for next time.

**Comment by PimDoos** [comment]
To make this a bit more intuitive, I added the minimum version to the HACS manifest in #50.  If you're installing the integration via HACS, it should now tell you that you need to upgrade to use this version of the integration.
