### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by basvanamerongen** [PimDoos/ha-sessy#83]
<img width="966" alt="image" src="https://github.com/PimDoos/ha-sessy/assets/153823550/c04f07f2-2880-4898-8f9d-06c2cfc90206">
Beste Pim,

sinds twee weken krijg ik Sessy niet meer gekoppeld aan Home assistant. Alle entities waren niet meer bereikbaar, uiteindelijk heb ik de installatie opnieuw gestart, de P1 en de sessie worden discovered als new device, maar als ik ze probeer te adden met UN en PW dan krijg ik de melding "unexpected error" Sessy en P1 uit en aanzetten helpt ook niet. Via portal.sessy werkt alles wel. Sessy helpdesk heeft geen idee. Heb jij nog een idee hoe ik dit kan fixen? groeten Bas

**Comment by PimDoos** [comment]
Kun je controleren of er in de logs een uitgebreidere foutmelding staat voor de Sessy integratie?

**Comment by basvanamerongen** [comment]
heb net HACS ook verwijderd en opnieuw geïnstalleerd, setup weer gedaan, debug aangezet, dit is wat ik uit de log haal.


2024-02-28 17:04:01.079 ERROR (MainThread) [custom_components.sessy.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/sessy/config_flow.py", line 94, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sessy/config_flow.py", line 34, in validate_input
    device = await get_sessy_device(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sessypy/devices.py", line 131, in get_sessy_device
    raise SessyNotSupportedException
sessypy.util.SessyNotSupportedException
2024-02-28 17:04:15.516 DEBUG (MainThread) [custom_components.hacs] <Integration PimDoos/ha-sessy> Getting repository information
2024-02-28 17:04:16.160 DEBUG (MainThread) [custom_components.hacs] <Integration PimDoos/ha-sessy> Running checks against v0.5.6
2024-02-28 17:04:16.851 DEBUG (MainThread) [custom_components.hacs] <Integration PimDoos/ha-sessy> Getting documentation for version=v0.5.6,filename=README.md
2024-02-28 17:04:16.852 DEBUG (MainThread) [custom_components.hacs] Trying to download https://raw.githubusercontent.com/PimDoos/ha-sessy/v0.5.6/README.md
2024-02-28 17:04:17.307 DEBUG (MainThread) [custom_components.hacs] <HacsData async_write> Saving data
2024-02-28 17:05:06.525 DEBUG (MainThread) [custom_components.hacs] <Integration PimDoos/ha-sessy> Getting repository information
2024-02-28 17:05:07.234 DEBUG (MainThread) [custom_components.hacs] <Integration PimDoos/ha-sessy> Running checks against v0.5.6
2024-02-28 17:05:07.913 DEBUG (MainThread) [custom_components.hacs] <Integration PimDoos/ha-sessy> Getting documentation for version=v0.5.6,filename=README.md
2024-02-28 17:05:07.913 DEBUG (MainThread) [custom_components.hacs] Trying to download https://raw.githubusercontent.com/PimDoos/ha-sessy/v0.5.6/README.md
2024-02-28 17:05:32.290 ERROR (MainThread) [custom_components.sessy.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/sessy/config_flow.py", line 94, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sessy/config_flow.py", line 34, in validate_input
    device = await get_sessy_device(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sessypy/devices.py", line 131, in get_sessy_device
    raise SessyNotSupportedException
sessypy.util.SessyNotSupportedException

**Comment by PimDoos** [comment]
Ik zie 'SessyNotSupportedException' in de log. Dit betekent meestal dat de integratie niet de juiste data terugkrijgt van de Sessy Dongle.
Ter controle: Zijn de Dongles bijgewerkt naar firmware 1.6.0 of hoger?
En kun je Sessy benaderen via de lokale URL?
http://sessy-ddee.local/update.html

**Comment by basvanamerongen** [comment]
Morning, dank voor je reactie, ik kan wel inloggen op de p1 meter en sessy, via de web gui’s benaderen, het lijkt erop dat de verbinding tussen home assistent box en sessy niet werkt. Ik zal vandaag het hele netwerk eens uit en aanzetten om te kijken of dit soelaas biedt

**Comment by basvanamerongen** [comment]
Morning, het is nu opgelost, heb alles uitgezet (router/switches/sessy/p1) en opnieuw gestart, installatie opnieuw gedaan in Home assistant en nu werkt het weer. Ik zie dat de ip adressen van de P1 en de Sessy zijn gewisseld, ik denk dat het hier ergens in gezeten heeft. Maar de klassieke alles uit en weer aan did the job. dank voor het meekijken
